apiVersion: v1
kind: Service
metadata:
  name: demo-python-app
  namespace: demo-python-app
  labels:
    app: demo-python-app
spec:
  type: NodePort
  selector:
    app: demo-python-app
  ports:
    - port: 80
      targetPort: 5000